import {Profile,Chairs,AddToCart,CheckCart,Checkout,Finish} from "./../PageObject/shopist"
require("cypress-xpath")
describe('Shopist',()=>{
    it('Complete Purchase',()=>{
        cy.visit('https://www.shopist.io')
        const pr = new Profile()
        const ch = new Chairs()
        const add = new AddToCart()
        const cc = new CheckCart()
        const co = new Checkout()
        const fi = new Finish()
        pr.seeProfile()
        ch.chairsSection()
        ch.selectChair()
        add.addToCart()
        cc.checkCart()
        co.checkout()
        fi.finish()
    })
    it('Complete Purchase',()=>{
        cy.visit('https://www.shopist.io')
        const pr = new Profile()
        const ch = new Chairs()
        const add = new AddToCart()
        const cc = new CheckCart()
        const co = new Checkout()
        const fi = new Finish()
        pr.seeProfile()
        ch.chairsSection2()
        ch.selectChair2()
        add.addToCart()
        cc.checkCart()
        co.checkout()
        fi.finish()
    })
})